{% set name = "geoserver-restconfig" %}
{% set version = "2.0.15" %}
{% set package_dir = "cb/ed/7fb361a0c9e34a3349501515901e7716de67881c939ac2527605a0cee7d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv https://files.pythonhosted.org/packages/{{ package_dir }}/geoserver_restconfig-{{ version }}-py3-none-any.whl
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - future
    - requests >=2.14.0
    - six >=1.12.0
    - gisdata >=0.5.4

test:
  imports:
    - geoserver
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/GeoNode/geoserver-restconfig
  summary: GeoServer REST Configuration
  description: A python library for manipulating a GeoServer instance via the GeoServer RESTConfig API.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://geonode.org/geoserver-restconfig/
  dev_url: https://github.com/GeoNode/geoserver-restconfig

extra:
  recipe-maintainers:
    - swainn
