{% set name = "geoserver-restconfig" %}
{% set version = "2.0.9" %}
{% set package_dir = "e8/1e/073ea55347ee701498e11c8f2a2ed65aa2e663ff8992c3afbbefae289c48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install -vv https://files.pythonhosted.org/packages/{{ package_dir }}/geoserver_restconfig-{{ version }}-py3-none-any.whl
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - future
    - requests
    - six
    - gisdata
    - urllib3 <2.0

test:
  imports:
    - geoserver
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GeoNode/geoserver-restconfig
  summary: GeoServer REST Configuration
  description: A python library for manipulating a GeoServer instance via the GeoServer RESTConfig API.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://geonode.org/geoserver-restconfig/
  dev_url: https://github.com/GeoNode/geoserver-restconfig

extra:
  recipe-maintainers:
    - swainn
